version: '3.3'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_USERNAME: 'docker'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - data:/var/lib/postgres/data

volumes:
  data:
